- environments/prod/prod.tfvars
> Add VH subscription

- README.md
- components/enterprise/subscriptions.tf
- components/video-hearings/subscriptions.tf
- components/video-hearings/variables.tf
- modules/environments/outputs.tf
- modules/environments/resource_group.tf
- modules/environments/service_plan.tf
- modules/subscription/acme.tf
- modules/subscription/locals.tf
- modules/subscription/service_principal.tf
- modules/subscription/variables.tf
- scripts/terraform-import.sh
Remove acme component
ACME component moved to https://github.com/hmcts/azure-enterprise-acme
Some resource moves and terraform import required
Adds Application.Read.All to bootstrap app reg to allow it to read ACME app reg in https://github.com/hmcts/azure-enterprise-acme
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Remove acme

- environments/prod/prod.tfvars
- scripts/terraform-import.sh
Add DCD-CFTAPPS-SBOX sub
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Import DCD-CFTAPPS-SBOX

- environments/prod/prod.tfvars
- scripts/terraform-import.sh
JIRA link (if applicable)
Change description
Add CFT Prod subs
Destruction in terraform plan is shuffling of group memberships due to counted resource
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> DTSPO-9746 - Add CFT Prod subs

- environments/prod/prod.tfvars
Importing sds sandbox and nonprod subs
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Add SDS Sandbox and NonProd subs

- environments/prod/prod.tfvars
- scripts/terraform-import.sh
Add SDS Prod subs
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Add SDS Prod subs

- environments/prod/prod.tfvars
- scripts/terraform-import.sh
Add Heritage and SOC subs
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Add Heritage and SOC subs

- README.md
Update readme
Changes are to remove owners which were added manually, this seems to not actually do anything
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Update readme

- azure-pipelines.yml
- modules/subscription/service_principal.tf
Update secret rotate schedule to 90 days
Add scheduled run in pipeline every day at 8am
Deletions are due to renaming resource. Same resource (time_rotating) will be recreated with more appropriate name
```
[ ] Yes
[x] No 
```
> DTSPO-9746 - Update rotate schedule

- environments/prod/prod.tfvars
Update management groups
```
[ ] Yes
[x] No
```
> DTSPO-9746 - Update management groups

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-11031
Adding Prod subscriptions to be imported. 
```
[ ] Yes
[x] No
```
> DTSPO-11030 - add production subscriptions ready for importing

- environments/prod/prod.tfvars
- scripts/subscriptions.json.example
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-11030
Change description
add subscriptions to the appropriate management groups
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> DTSPO-11030 Import unassigned subscriptions to -NonProd

- environments/prod/prod.tfvars
- scripts/subscriptions.json.example
- scripts/terraform-import.sh
https://tools.hmcts.net/jira/browse/DTSPO-11030
updating env for some subscriptions
```
[ ] Yes
[x] No
```
> Dtspo 11030 import unassigned subscriptions to terraformstate non prod

- components/enterprise/environments.tf
- components/enterprise/subscriptions.tf
- components/enterprise/variables.tf
- components/video-hearings/environments.tf
- components/video-hearings/subscriptions.tf
- components/video-hearings/variables.tf
Set expiresAfter tag to 3000-01-01 so sandbox resources do not get deleted
```
[ ] Yes
[x] No
```
> DTSPO-11790 - add expiresAfter tag

- modules/management-group-bootstrap/readers.tf
- modules/subscription/role_assignments.tf
Currently, Application Gateway Backend Health Reader role is being constantly deleted and recreated due to the subscriptions/subscription-id/ part of the resource id being missing.
Updating path so no changes occur.
> Update custom roles resource id for subscriptions

- environments/prod/prod.tfvars
Might need a few resources moved around
```
[ ] Yes
[x] No
```
> Try fixing ptlsbox environment

- README.md
Used to remove 2 cancelled subscriptions today, they had like 30 resources each...
> Script to remove old subscriptions from state

- README.md
- environments/prod/prod.tfvars
- scripts/terraform-import.sh
https://tools.hmcts.net/jira/browse/DTSPO-15482
> feat: added heritage int svc dev

- README.md
- components/enterprise/subscriptions.tf
- environments/prod/prod.tfvars
- modules/subscription/service_principal.tf
- modules/subscription/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-16190
Added Purview API permissions to SHAREDSERVICES-DEV SP.
> feat: added ability to define additional api permissions for service principals

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DC-250
Grants delegated Purview api access to dts-sharedservices-prod SP. Done previously in dev as mentioned in JIRA
> Adding api permissions for purview

- modules/management-group-bootstrap/reservation-purchaser.tf
- modules/management-group-bootstrap/reservations-purchaser.tf
add reservations purchaser
- Required for Bhuvan Purushothaman (FinOps)
> add reservations purchaser

- README.md
https://tools.hmcts.net/jira/browse/DTSPO-17071
Updated read me with reasons why we have to live with PAT tokens :(
> DTSPO-17071 - updating Read Me

- components/enterprise/provider.tf
- components/video-hearings/provider.tf
- modules/subscription/groups.tf
- modules/subscription/keyvault.tf
- modules/subscription/locals.tf
- modules/subscription/main.tf
- modules/subscription/role_assignments.tf
Update Enterprise component azurerm provider version to fix MS timeinsights bug
> Update Enterprise component azurerm provider version to fix MS timeinsights bug

- modules/management-group-bootstrap/storage-blob-data-contributor.tf
Add role Storage Blob Data Contributor
> Add role Storage Blob Data Contributor

- README.md
- environments/prod/prod.tfvars
N/A
Renoving a couple of subscriptions from the code that no longer exist in the portal
Trying to fix an error in the pipeline which is preventing it from succeeding
Pipeline hasn't succeeded since August and it should run every day.
Destroys in the plan are from resources that have already been removed mostly as the subs were deleted a while ago
The creates are from changes made since August that were never applied
> Remove deleted subs

- components/video-hearings/removed.tf
Remove resources like key vault secrets that do not exist anymore but are still picked up by terraform
> Remove deleted VH resources
